// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    401: typeof import('./src/components/error/401/index.vue')['default']
    403: typeof import('./src/components/error/403/index.vue')['default']
    404: typeof import('./src/components/error/404/index.vue')['default']
    500: typeof import('./src/components/error/500/index.vue')['default']
    503: typeof import('./src/components/error/503/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Hover: typeof import('./src/components/animation/hover/index.vue')['default']
    Language: typeof import('./src/components/layouts/language/index.vue')['default']
    Lock: typeof import('./src/components/admin/lock/index.vue')['default']
    Login: typeof import('./src/components/login/login/index.vue')['default']
    Message: typeof import('./src/components/admin/message/index.vue')['default']
    Refresh: typeof import('./src/components/layouts/refresh/index.vue')['default']
    ResetPassword: typeof import('./src/components/login/resetPassword/index.vue')['default']
    Screen: typeof import('./src/components/layouts/screen/index.vue')['default']
    Setting: typeof import('./src/components/layouts/setting/index.vue')['default']
    Signup: typeof import('./src/components/login/signup/index.vue')['default']
    Unfold: typeof import('./src/components/layouts/unfold/index.vue')['default']
    User: typeof import('./src/components/layouts/user/index.vue')['default']
    UserInfo: typeof import('./src/components/admin/userInfo/index.vue')['default']
  }
}

export { }
